### PR TITLE
Add new error levels (off, warn, error)

### LINKED ISSUE #98: Add a "Warn" state
Some linting tools provide 3 states:
**"off":** rule is off
**"warn":** rule is displayed in output, but doesn't trigger exit code
**"error":** rule is displayed in output and triggers an exit code (exit 1)

This would help for situations such as "note" errors or "line-length" errors. For example, if I write a `todo` in my project, I likely want to be reminded to finish the "todo" section, but in vala-lint's current state, my project will have a failing lint setup. By adding a warn state, my vala-lint output can remind me of the todo, without failing the entire check.

Another good example would be setting line-length to warn in an existing project. This way, the project doesn't have to have `// vala-lint=line-length` at the end of the offending line, the ci step can still pass, and users can still be reminded about the length of the line.

Some prior art:
[Eslint's Rule Config](https://eslint.org/docs/user-guide/configuring#configuring-rules)
[Checkstyle's Severity](https://checkstyle.sourceforge.io/config.html#Severity)

### PR DESCRIPTION
**Pull request by kgrubb**
This is a first attempt at adding a "warn" state.

I'm super new to Vala, so by all means, feel free to critique! The scope here is to be able to set default levels to errors, and only send failure exit codes on errors, while displaying output for warnings.

### Examples

For the examples below, I've also run `echo $?` just to show the related exit code.

Here's an example with both warnings and errors:

Screenshot from 2019-09-16 14-05-56

An example of just warnings:

Screenshot from 2019-09-16 14-06-13

An example of no warnings/errors:

Screenshot from 2019-09-16 14-06-21

Resolves #98.

### CODE REVIEW

**Comment by kgrubb** [comment]
Another example screenshot from an existing application:

Screenshot from 2019-09-16 16-18-32

**Comment by pantor** [comment]
Hi @kgrubb, that's a great start!

I would suggest to wait till #89 is merged, since there are already some overlapping parts like a check level implemented. Then, you can build upon that to e.g. print the mistake level.

**Comment by kgrubb** [comment]
:+1: sounds good, I'll wait and rebase off of master once #89 is finished!

**Comment by kgrubb** [comment]
actually, #89 resolves most of this aside from showing the check state in the output. clsoing this in favor of making a different pr with just the print stuff.

**Pull request closed without merging**
