### PR TITLE
tests: Run tests with G_DEBUG=fatal-warnings

### PR DESCRIPTION
**Pull request by ricotz**

### CODE REVIEW

**Comment by ricotz** [comment]
@kgrubb Did you give it some thoughts?

**Comment by kgrubb** [comment]
Hey @ricotz, unfortunately this is a bit over my head, perhaps @pantor may be more knowledgeable on the changes in this pr?

**Comment by ricotz** [comment]
@kgrubb It is not strictly about the changes, but the way the test-suite works.

Manually creating Vala symbols might be too error prone. And using actual code-snippets would be better. That way a proper Vala AST can be used.

**Comment by pantor** [comment]
I've moved all unit tests to file tests, so we don't creating Vala symbols manually anymore.

**Comment by ricotz** [comment]
@pantor Please fix these warnings.

```shell
$ _build/src/io.elementary.vala-lint 
.test/FileTest.vala
   38.120   warn    Line exceeds limit of 120 characters (currently 129 characters)   line-length
   53.120   warn    Line exceeds limit of 120 characters (currently 151 characters)   line-length
   56.120   warn    Line exceeds limit of 120 characters (currently 155 characters)   line-length
   64.120   warn    Line exceeds limit of 120 characters (currently 154 characters)   line-length
   67.120   warn    Line exceeds limit of 120 characters (currently 151 characters)   line-length
   70.120   warn    Line exceeds limit of 120 characters (currently 169 characters)   line-length
   73.120   warn    Line exceeds limit of 120 characters (currently 163 characters)   line-length
   76.120   warn    Line exceeds limit of 120 characters (currently 154 characters)   line-length
```

**Comment by pantor** [comment]
Warnings should be all fixed now.

**Pull request merged**
