### PR TITLE
Add tests for autofix functionality

### PR DESCRIPTION
**Pull request by dar5hak**
Courtesy @colinkiama.

Ignore the previous commits; they are there because we reused the same branch as #146.

### CODE REVIEW

**Comment by dar5hak** [comment]
@colinkiama Any idea what's going on here?

```
ERROR:../test/AutoFixTest.vala:90:auto_fix_test_prepare_files_for_test: assertion failed: (output_dir.query_exists ())
```

**Comment by colinkiama** [comment]
I forgot that I created some directories manually instead of generating them in-code.

I've fixed those issues in this branch: https://github.com/colinkiama/vala-lint/blob/master/test/AutoFixTest.vala

**Comment by dar5hak** [comment]
@colinkiama Can you merge it to `autofix` branch? I have given you access.

**Comment by colinkiama** [comment]
Checks passed :+1:

**Review by kgrubb — APPROVED** [review]

**Pull request merged**
