### PR TITLE
Fix Slicing Error in NoteCheck

### LINKED ISSUE #101: Slicing error possible in NoteCheck.vala
This line 

`        // Improve error management FIXME`

gives rise to a GLib assertion failure from slice () and some other functions that `start` must be less than or equal to `end`.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/80456374-slicing-error-possible-in-notecheck-vala?utm_campaign=plugin&utm_content=tracker%2F45980444&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F45980444&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pantor**
Fixes #101 by generating the correct message after a note.

### CODE REVIEW

**Comment by kgrubb** [comment]
I added the following to a vala file:
```vala
// TODO: This is an example todo to trigger vala-lint
```

On master, this is the output:

Screenshot from 2019-09-19 15-56-37

On this branch, the output looks a little bit different:

Screenshot from 2019-09-19 15-56-28

**Comment by pantor** [comment]
I've now added the ability to disable checks for an entire file by setting `// vala-lint=skip-file`. This way, I could improved the test file so that we can check for the note message directly. All in all, I hope this is fixed now :wink:

**Comment by kgrubb** [comment]
lgtm!
Screenshot from 2019-09-20 16-36-42

**Comment by kgrubb** [comment]
Using these examples:
Screenshot from 2019-09-20 16-38-25

I get the following:
Screenshot from 2019-09-20 16-38-18

**Pull request merged**
